from pathlib import Path
import json
import pandas as pd
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.section import WD_SECTION
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_CELL_VERTICAL_ALIGNMENT
from docx.oxml import OxmlElement
from docx.oxml.ns import qn

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "submission" / "information_fusion_manuscript_package.docx"

def shade(cell, fill):
    tcPr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd"); shd.set(qn("w:fill"), fill); tcPr.append(shd)

def set_cell(cell, text, bold=False):
    cell.text = ""
    p = cell.paragraphs[0]; p.paragraph_format.space_after = Pt(0)
    r = p.add_run(str(text)); r.bold = bold; r.font.size = Pt(8)
    cell.vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER

def add_table(doc, headers, rows):
    table = doc.add_table(rows=1, cols=len(headers)); table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table.style = "Table Grid"
    for i, h in enumerate(headers):
        set_cell(table.rows[0].cells[i], h, True); shade(table.rows[0].cells[i], "D9EAF7")
    for row in rows:
        cells = table.add_row().cells
        for i, value in enumerate(row): set_cell(cells[i], value)
    doc.add_paragraph().paragraph_format.space_after = Pt(2)
    return table

def add_body(doc, text):
    for block in text.strip().split("\n\n"):
        if not block.strip(): continue
        p = doc.add_paragraph()
        p.paragraph_format.space_after = Pt(6)
        p.paragraph_format.line_spacing = 1.08
        p.add_run(block.strip())

def add_heading(doc, text, level=1):
    p = doc.add_heading(text, level=level)
    p.paragraph_format.keep_with_next = True
    return p

def main():
    doc = Document()
    sec = doc.sections[0]; sec.top_margin = Inches(0.8); sec.bottom_margin = Inches(0.8); sec.left_margin = Inches(0.85); sec.right_margin = Inches(0.85)
    styles = doc.styles
    styles["Normal"].font.name = "Arial"; styles["Normal"].font.size = Pt(10)
    for name, size in [("Title", 20), ("Heading 1", 14), ("Heading 2", 11)]:
        styles[name].font.name = "Arial"; styles[name].font.size = Pt(size); styles[name].font.color.rgb = RGBColor(0,0,0)

    title = doc.add_paragraph(); title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.add_run("When More Omics Is Not Always Better: Drug- and Dataset-Conditional Value of Multimodal Cancer Pharmacogenomics"); run.bold = True; run.font.size = Pt(20); run.font.color.rgb = RGBColor(0,0,0)
    p = doc.add_paragraph(); p.alignment = WD_ALIGN_PARAGRAPH.CENTER; p.add_run("Carlos Victor Montefusco-Pereira\n").bold = True; p.add_run("Independent Researcher in Data Science and AI for Pharmaceutical Industry\nFriedrich-Wilhelm 28, 12103 Berlin, Germany\nCorresponding author: cmontefusco@gmail.com")
    doc.add_paragraph()
    p = doc.add_paragraph(); p.add_run("Article type: ").bold = True; p.add_run("Research article")
    p = doc.add_paragraph(); p.add_run("Declarations: ").bold = True; p.add_run("No external funding. The author declares no competing interests. Ethics approval is not applicable because the study uses publicly available, de-identified cell-line and molecular datasets and involves no human participants, patient intervention, or animal experimentation. CRediT: Carlos Victor Montefusco-Pereira—Conceptualization, Methodology, Software, Validation, Formal analysis, Investigation, Data curation, Writing, Visualization, and Project administration. Generative AI tools assisted with language editing, document formatting, and coding under author review; the author verified the final content. DepMap/GDSC/CTD² files were obtained under the provider’s applicable terms; raw provider files are not redistributed.")
    doc.add_page_break()

    add_heading(doc, "Abstract", 1)
    add_body(doc, "Multimodal molecular profiles are often assumed to improve cancer drug-response prediction simply by adding information. We developed an evidence-bounded DepMap workflow to test that assumption across expression, copy-number, and mutation features. The declared evaluation universe contained 15 compounds from GDSC1, GDSC2, and CTD². Models used fold-local feature selection and Ridge regression, with drug-held-out and leave-one-dataset-out validation. In full-universe drug-held-out validation across five repeated splits, fusion had mean RMSE 0.2322 versus 0.2328 for expression alone (mean fusion-minus-expression RMSE −0.0006; seed-level SD 0.0013). Fusion improved in three of five splits and was slightly worse in two. In cross-study validation, fusion was slightly worse in all three held-out datasets: CTD² 0.3238 versus 0.3231, GDSC1 0.2339 versus 0.2322, and GDSC2 0.2387 versus 0.2347. Structured missingness and weak-to-moderate row-level modality correlations accompanied dataset-sensitive performance. These findings support evaluating multimodal models by incremental value, transferability, and failure modes rather than assuming that more omics is always better.")
    p = doc.add_paragraph(); p.add_run("Keywords: ").bold = True; p.add_run("information fusion; drug response; multi-omics; cancer; missing data; cross-study validation")

    add_heading(doc, "1. Introduction", 1)
    add_body(doc, "Cancer pharmacogenomics increasingly combines multiple molecular assays to predict drug response. More measurements can capture complementary biology, but they also increase dimensionality, missingness, and sensitivity to study-specific measurement processes. We therefore specified a workflow that treats incremental predictive value, missingness, and modality conflict as joint evaluation targets.")
    add_heading(doc, "1.1. Brief literature context", 2)
    add_body(doc, "Drug response is a heterogeneous phenotype shaped by lineage, genomic alterations, transcriptional state, assay conditions, and drug-specific mechanisms. The Cancer Cell Line Encyclopedia established a large-scale link between cancer cell-line molecular profiles and pharmacologic sensitivity [1]. The Genomics of Drug Sensitivity in Cancer subsequently provided a broad pharmacogenomic map across drugs and cell lines, showing that response associations are distributed across tissue context and molecular features rather than being reducible to a single biomarker class [2]. DepMap and related resources further consolidated molecular and functional measurements for systematic cancer-model analysis [3]. These resources made computational response prediction possible, but they also made the data-integration problem more visible: assays are not uniformly measured across all models, and response data are generated under source-specific experimental protocols.")
    add_body(doc, "For pharmaceutical research, the relevant endpoint is not only predictive accuracy but whether a model can support transparent prioritization of compounds, biomarkers, and follow-up experiments. A model that performs reliably across a declared validation target may help rank candidate molecular contexts for early discovery studies; however, cell-line prediction alone does not establish clinical utility, prospective benefit, or suitability for dosing decisions. These boundaries motivate an evaluation that reports transfer failures and data-availability constraints alongside average error metrics.")
    add_body(doc, "The literature contains several complementary modeling strategies. Expression-only models have often been competitive because transcriptomic state captures pathway activity and lineage context, whereas mutation and copy-number features can provide sparse but mechanistically informative signals. Multimodal models combine these signals through early concatenation, late integration, multitask learning, or biologically structured architectures. MOLI, for example, integrates expression, copy-number, and mutation information through modality-specific encoders and reported gains in external validation [5]. DrugCell uses a biologically structured neural network and drug representations to model response and synergy [8], while other deep-learning frameworks have reported strong performance in cell-line settings and more variable transfer to clinical or external cohorts [9,10]. These results motivate multimodal integration, but they do not imply that adding an assay is beneficial under every population, response definition, or validation design.")
    add_body(doc, "The practical question is therefore not whether a modality is biologically informative in isolation, but whether it adds reliable information after the strongest available baseline and the data-construction rules have been fixed. An additional block may improve predictions because it captures complementary biology, because it changes the effective regularization of the learner, or because it changes which rows and features are usable. These explanations have different implications for deployment. A gain that depends on complete-case filtering, a particular response scale, or a shared source protocol may not survive when the model is moved to another screening resource. Conversely, a small gain that persists under entity-level holdout could be useful even if it does not imply a mechanistic contribution from every included feature.")
    add_body(doc, "This distinction also matters for interpreting negative results. A fusion model that fails to improve a compact expression baseline does not show that copy-number or mutation data are irrelevant. It may indicate that the chosen learner, feature budget, imputation rule, or response universe did not convert those measurements into additional predictive accuracy. The appropriate conclusion is consequently conditional: the benchmark estimates incremental value under a declared construction, rather than ranking the biological importance of the assays themselves. We designed the analysis around that narrower estimand.")
    add_body(doc, "There are three reasons to be cautious when comparing such results. First, the prediction target can change from continuous viability or IC50 to a binary responder label, making error metrics and biological interpretations non-equivalent [4,5]. Second, random splitting of cell-line–drug pairs can place related observations, or the same cell-line molecular profile, on both sides of a split; this can answer an easier question than prediction for an unseen drug or a new study. Recent work has explicitly identified leakage risks from random tuple splits in drug-response modeling [9]. Third, feature selection and preprocessing performed before validation can leak information from held-out observations even when model fitting itself is separated. These concerns are particularly important in high-dimensional multi-omics data, where dimensionality and preprocessing choices materially affect model behavior [6,7].")
    add_body(doc, "Published comparisons therefore leave a practical gap: it remains difficult to tell whether a reported multimodal gain reflects complementary biology, a favorable split, source-specific assay coverage, or preprocessing choices. Cross-study transfer is also less frequently treated as a primary test than within-dataset cross-validation, despite differences in response scales, cell-line coverage, and molecular measurement between screening resources. We address this gap with a deliberately modest benchmark: the same Ridge learner, the same feature budget, fold-local selection from the full raw modality universe, explicit single-modality baselines, drug-held-out evaluation, and leave-one-dataset-out transfer. The aim is not to outperform deep-learning systems, but to estimate the incremental value of adding modalities under a transparent and leakage-controlled comparison.")
    add_heading(doc, "1.2. Research questions and hypotheses", 2)
    add_body(doc, "We asked three questions: (Q1) Does feature-level fusion improve prediction when drugs, rather than cell lines alone, are held out? (Q2) Does any improvement transfer when an entire response dataset is held out? (Q3) Are fusion effects accompanied by structured missingness or modality redundancy? We specified the following directional expectations before interpreting the results: H1, fusion may improve drug-held-out prediction relative to expression alone; H2, fusion gains may not transfer across datasets; and H3, missingness and redundancy may vary across source datasets and coincide with unstable fusion effects. These are benchmark hypotheses, not claims of biological causality.")

    add_heading(doc, "2. Methods", 1)
    add_body(doc, "We harmonized DepMap response and molecular data from GDSC1, GDSC2, and CTD² using release identifiers recorded in the repository manifest. The response variable was the source-provided AUC value; response scales were retained by source and were not interpreted as identical assay measurements. Expression, copy-number, and damaging-mutation features were evaluated separately and in concatenated fusion models. Within each held-out fold, the top 2,000 features per modality were selected from the complete raw feature universe using training rows only. Models used training-fold median imputation, training-fold standardization, and Ridge regression with alpha = 1.0. Drug-held-out splits grouped rows by drug; leave-one-dataset-out folds held out each source dataset in turn. Outer joins were retained for structured missingness analyses.")
    add_heading(doc, "2.1. Evaluation scope", 2)
    add_body(doc, "The declared evaluation universe contains 15 compounds: five from GDSC1, five from GDSC2, and five from CTD². This is a declared cross-dataset subset, not the complete drug universe available in any one portal release. The exact compound identifiers, source-specific row counts, and cell-line counts are provided in Supplementary Table S1. Because the datasets do not contain a broad common set of identical compounds, leave-one-dataset-out results measure cross-study transfer rather than same-drug replication.")
    add_heading(doc, "2.2. Metrics and interpretation", 2)
    add_body(doc, "We report mean absolute error (MAE) and root mean squared error (RMSE). Fusion deltas are defined as fusion RMSE minus expression RMSE; negative values favor fusion and positive values favor expression. Missingness strata are descriptive availability strata, not a replacement for imputation-aware model evaluation. All formal result tables and split manifests are versioned with the workflow.")
    add_heading(doc, "2.3. Dataset harmonization and response definition", 2)
    add_body(doc, "The workflow treats the response table as the analysis backbone and joins molecular features through stable cell-line identifiers. Drug identifiers were normalized within source datasets before defining the declared compound universe. The analysis does not assume that nominally similar compounds across sources are interchangeable. Consequently, source-specific response measurements remain associated with their originating dataset, and leave-one-dataset-out evaluation is interpreted as a domain-transfer test.")
    add_heading(doc, "2.4. Feature construction and leakage control", 2)
    add_body(doc, "Expression, copy-number, and damaging-mutation matrices were processed as separate modality blocks. Feature selection was repeated inside every training fold, using only training-row variance and the declared feature budget. The selected blocks were then imputed and standardized using training-derived quantities before model fitting. Test rows were transformed with those fitted quantities. This ordering prevents response information from the held-out drugs or datasets from influencing feature selection or preprocessing.")
    add_heading(doc, "2.5. Model specification and baselines", 2)
    add_body(doc, "Each modality was evaluated as a standalone baseline, and fusion was defined as concatenation of the selected expression, copy-number, and mutation blocks. All models used the same Ridge estimator and alpha value so that the comparison isolates the effect of adding blocks rather than changing the learner. This deliberately conservative design does not claim that Ridge is optimal; it provides a reproducible reference against which more flexible fusion methods can be compared.")
    add_body(doc, "This is a fixed-learner fusion ablation rather than a state-of-the-art model comparison. It does not include drug chemical structure, drug-target information, pathway representations, imaging, foundation-model embeddings, or learned modality-completion modules. The design therefore isolates the incremental value of the three cell-line molecular blocks under one transparent model specification.")
    add_heading(doc, "2.6. Split manifests and reproducibility", 2)
    add_body(doc, "Five drug-held-out manifests were persisted before model evaluation. Grouped splitting prevents rows from the same drug from appearing in both training and test partitions. The leave-one-dataset-out manifests hold out one complete response source at a time. Result JSON files retain the seed, row counts, selected-feature counts, model label, and error metrics. The supplementary package provides the complete manifest and artifact inventory needed to audit these choices.")
    add_heading(doc, "2.7. Analysis sequence and implementation controls", 2)
    add_body(doc, "The analysis sequence was fixed before interpreting performance: define the 15-compound response universe; normalize dataset and cell-line identifiers; construct outer-joined modality tables for availability auditing; create grouped split manifests; select features using training rows only; fit training-derived imputation and scaling; fit the same Ridge specification for each modality; and calculate held-out MAE and RMSE. No test response values were used for feature ranking, imputation, scaling, or model selection. The formal comparisons therefore estimate the incremental predictive value of concatenating modality blocks under a common pipeline, not the value of a separately tuned learner for each modality.")
    add_body(doc, "All formal seeds, selected-feature manifests, row counts, and model metrics are retained as machine-readable artifacts. The clean-environment rerun used the locked dependency specification and regenerated the reported tables and figures. Earlier candidate-table and cell-line-held-out analyses are retained as exploratory history and are not used for the manuscript headline claims.")

    add_heading(doc, "3. Results", 1)
    add_heading(doc, "3.1. Drug-heldout validation", 2)
    add_body(doc, "Drug-held-out performance was small and seed-sensitive across five full-universe splits. The mean RMSE across seeds was 0.2322 for fusion versus 0.2328 for expression alone; this arithmetic mean is not a pooled observation-level RMSE and should not be interpreted as a universal gain. Per-seed and per-model values are reported in Table 2 and Supplementary Table S3.")
    add_body(doc, "As a secondary diagnostic, a training-set mean-response baseline was worse than expression and fusion in four of five seeds; in the fifth seed it was better than both. A per-drug audit covered eight unique held-out compounds across 15 drug-seed cells; fusion improved RMSE in 11 cells and worsened it in four. Because compounds recur across seeds and only three drugs are held out per split, this audit is descriptive rather than an independent estimate of generalization.")
    add_heading(doc, "3.2. Cross-study transfer", 2)
    add_body(doc, "In leave-one-dataset-out validation, expression was consistently stronger than fusion, with the largest fusion degradation on CTD². These folds test transfer across source datasets, not replication of the same drug. The signed fusion-minus-expression RMSE deltas are shown in Figure 2 and Supplementary Table S4.")
    add_body(doc, "The magnitude of the transfer differences should be read together with the source-specific row counts and response construction. The held-out datasets are not interchangeable partitions of one identical experiment: they differ in compound composition, cell-line coverage, assay procedures, and the availability of molecular blocks. Thus, the LOOD comparison asks whether the complete modeling pipeline transfers to a new response source, not whether the same drug effect is reproduced in a second assay. This makes the result a stress test for portability, while also limiting the specificity of any explanation for the observed degradation.")
    add_heading(doc, "3.3. Missingness and redundancy", 2)
    add_body(doc, "Row-level modality summaries showed weak-to-moderate correlations, while outer-joined tables showed dataset-dependent modality availability. These analyses describe data structure and model behavior; they do not establish that missingness or redundancy caused the observed performance differences.")
    add_body(doc, "The outer-join audit found mean availability of 0.827 for expression, 0.594 for copy number, and 0.995 for damaging mutation, with 0.591 of rows complete across all three blocks. These values are calculated from the prepared outer-joined tables before fold-specific feature selection. They describe the 15-compound tables and selected cell-line intersection, not complete-case availability of the selected fold-specific 2,000-feature blocks, portal-wide availability, or clinical assay availability. Models retained incomplete rows through training-fold median imputation.")
    lood = json.loads((ROOT/"data/processed/full_universe_lood_results.json").read_text())
    rows=[]
    for d,f in lood["folds"].items(): rows.append([d, f["metrics"]["expression"]["rmse"], f["metrics"]["copy_number"]["rmse"], f["metrics"]["mutation"]["rmse"], f["metrics"]["fusion"]["rmse"]])
    p=doc.add_paragraph(); p.add_run("Table 1. ").bold=True; p.add_run("Leave-one-dataset-out RMSE.")
    add_table(doc,["Held-out dataset","Expression","Copy number","Mutation","Fusion"], [[r[0]]+[f"{x:.4f}" for x in r[1:]] for r in rows])
    p=doc.add_paragraph(); p.add_run("Table 2a. ").bold=True; p.add_run("Declared compounds and response-row counts.")
    compounds=[]
    for (dataset, drug), n in pd.read_csv(ROOT/"data/processed/combined_15drug_outer_table.csv", usecols=["dataset_id","drug_id_raw"]).groupby(["dataset_id","drug_id_raw"]).size().items():
        compounds.append([dataset, drug, str(int(n))])
    add_table(doc,["Dataset","Compound","Response rows"], compounds)
    drug_rows=[]
    for seed in ["20260821","20260822","20260823","20260824","20260825"]:
        d=json.loads((ROOT/f"data/processed/full_universe_{seed}.json").read_text()); drug_rows.append([seed, f"{d['metrics']['expression']['rmse']:.4f}", f"{d['metrics']['fusion']['rmse']:.4f}", f"{d['metrics']['fusion']['rmse']-d['metrics']['expression']['rmse']:+.4f}"])
    p=doc.add_paragraph(); p.add_run("Table 2. ").bold=True; p.add_run("Drug-held-out repeated-seed RMSE.")
    add_table(doc,["Seed","Expression","Fusion","Fusion delta"],drug_rows)
    p=doc.add_paragraph(); p.add_run("Table 3. ").bold=True; p.add_run("Drug-held-out MAE and RMSE by model and seed.")
    all_rows=[]
    for seed in ["20260821","20260822","20260823","20260824","20260825"]:
        d=json.loads((ROOT/f"data/processed/full_universe_{seed}.json").read_text())
        for model in ["expression","copy_number","mutation","fusion"]:
            m=d["metrics"][model]
            all_rows.append([seed, model, f"{m['mae']:.4f}", f"{m['rmse']:.4f}", str(m.get("n_features", 2000 if model != "fusion" else 6000))])
    add_table(doc,["Seed","Model","MAE","RMSE","Selected features"],all_rows)
    doc.add_page_break()
    p=doc.add_paragraph(); p.add_run("Table 4. ").bold=True; p.add_run("Leave-one-dataset-out MAE, RMSE, and evaluation strata.")
    lood_rows=[]
    for dname,f in lood["folds"].items():
        for model in ["expression","copy_number","mutation","fusion"]:
            m=f["metrics"][model]
            lood_rows.append([dname, model, str(f["train_rows"]), str(f["test_rows"]), f"{m['mae']:.4f}", f"{m['rmse']:.4f}"])
    add_table(doc,["Held-out dataset","Model","Train rows","Test rows","MAE","RMSE"],lood_rows)
    for image, caption in [(ROOT/"outputs/figures/lood_rmse.png","Figure 1. Leave-one-dataset-out performance."),(ROOT/"outputs/figures/modality_conflict.png","Figure 2. Fusion minus expression RMSE across held-out folds."),(ROOT/"outputs/figures/composite_validation.png","Figure 3. Composite summary of transfer performance, signed fusion deltas, and structured modality availability.")]:
        doc.add_picture(str(image), width=Inches(6.5)); p=doc.paragraphs[-1]; p.alignment=WD_ALIGN_PARAGRAPH.CENTER; cap=doc.add_paragraph(caption); cap.alignment=WD_ALIGN_PARAGRAPH.CENTER

    add_heading(doc, "4. Discussion", 1)
    add_body(doc, "The results do not support a universal multimodal advantage. Fusion can help within a drug-held-out universe yet fail under study transfer, consistent with domain-specific response scales, assay coverage, and feature distributions. This pattern is compatible with prior reports that multimodal integration can improve prediction under particular data and validation settings [5,8], while benchmarking work shows variation across algorithms, drugs, and transfer targets [9,10]. Our controlled comparison adds a more modest observation: the incremental fusion effect is small within the declared drug-held-out benchmark and reverses direction under source-dataset transfer. This does not refute multimodal modeling; it shows why a gain observed in one validation regime should not be generalized to another without direct testing. The study is limited by the small declared 15-drug universe, limited same-drug overlap across datasets, and the use of compact Ridge baselines rather than a broad model class.")
    add_body(doc, "H1 was only partially supported: fusion improved the mean across five drug-held-out seeds, but the sign was favorable in three seeds and unfavorable in two. H2 was supported in this evaluation: fusion degraded performance in all three leave-one-dataset-out folds. H3 was supported descriptively because modality availability and row-level correlations differed across source tables, but the study does not identify a causal explanation. These findings argue for reporting effect size and transfer failures alongside the direction of the fusion comparison.")
    add_body(doc, "The methodological implication is that validation design is part of the scientific claim. A random cell-line–drug split can estimate interpolation within an existing response system, whereas a drug-held-out split asks whether molecular features support prediction for compounds not represented in training. A leave-one-dataset-out split adds a different stress test: it asks whether the learned relationship survives a change in source, assay, and coverage. These estimands should not be conflated. Our study uses them sequentially to show that the answer to ‘does fusion help?’ depends on which generalization target is intended.")
    add_body(doc, "For early drug discovery and biomarker prioritization, the practical implication is a decision-support role rather than an autonomous selection rule. Expression-only models may be preferable when they provide similar accuracy with broader availability and lower maintenance burden; additional modalities should be retained when they yield reproducible gains for a clearly defined use case. The present analysis does not test prospective compound prioritization, biomarker clinical validity, manufacturing decisions, or patient treatment selection, so these implications remain hypotheses for future validation.")
    add_body(doc, "The small size of the observed within-universe effect is itself informative for model development. The mean difference is much smaller than the variation in absolute RMSE across seeds, and the direction changes in two of five comparisons. This pattern does not justify selecting fusion solely because its arithmetic mean is lower. A reasonable decision rule would also consider the cost of obtaining and maintaining the extra modalities, the completeness of those modalities in the intended population, and whether the improvement is reproduced under a declared external test. Under the present evidence, expression remains a competitive reference and fusion is best treated as a candidate extension requiring further validation.")
    add_body(doc, "The analysis also suggests a reproducibility principle for future information-fusion studies: preserve the split manifests and the feature-selection scope as first-class artifacts. Without them, a later rerun can silently change the estimand while retaining the same model name and headline metric. Reporting the sign of each fold-level delta, rather than only an aggregate score, makes such changes easier to detect. This is particularly important when the expected effect is small, as in the present benchmark.")
    add_heading(doc, "4.1. Interpretation of the within-dataset result", 2)
    add_body(doc, "The drug-held-out result is compatible with a limited benefit from complementary features when the training and test rows share a source-defined response system. Fusion improved the mean across five seeds, but only three of five seed-level comparisons favored fusion and the effect sizes were small relative to the absolute error. We therefore describe this result as uncertain, conditional evidence that fusion can be useful under a matched evaluation regime, not as evidence that fusion should replace a strong single-modality baseline.")
    add_heading(doc, "4.2. Interpretation of cross-study degradation", 2)
    add_body(doc, "The consistent cross-study degradation is the most important cautionary result. It may reflect differences in assay design, response scaling, compound composition, cell-line coverage, molecular measurement, or feature distributions. The present benchmark does not separate these explanations. It does show that a model selected for within-universe performance can lose accuracy when the response source changes, which makes transfer validation necessary for claims about general-purpose multimodal prediction.")
    add_heading(doc, "4.3. Missingness, redundancy, and model choice", 2)
    add_body(doc, "The outer-join analysis shows that the usable intersection of modalities differs by dataset. A complete-case fusion analysis can therefore change the population being evaluated before any model is fitted. Conversely, median imputation preserves rows but may weaken modality-specific structure. The current analysis reports both availability and model performance, but it does not compare missingness-aware architectures, learned imputation, modality dropout, or late-fusion weighting. Those are appropriate follow-up tests rather than conclusions supported here.")
    add_heading(doc, "4.4. Relation to prior multimodal work", 2)
    add_body(doc, "The findings do not contradict prior reports that multimodal integration can improve drug-response prediction under particular data and validation settings [4–6,8]. Recent reviews and benchmarking frameworks further emphasize drug representations, missing-modality handling, broader metric sets, and clinically relevant validation designs [11–13]. Instead, they emphasize that the reported gain is inseparable from the response universe, split strategy, preprocessing, and transfer target. The distinction is especially relevant when a study combines data sources that differ in coverage or measurement. A fair comparison should therefore report the single-modality baseline, fold-local processing, held-out entities, and the direction and size of the fusion delta. In practical terms, a multimodal model should be retained only when its incremental accuracy is large enough, stable enough, and transferable enough to justify the added data requirements.")
    add_heading(doc, "4.5. Limitations and next experiments", 2)
    add_body(doc, "The principal limitations are the 15-compound evaluation universe, the limited overlap of identical drugs across datasets, the use of a fixed Ridge model, the descriptive per-drug audit with eight unique held-out compounds across repeated seed-specific cells, and the absence of prospective experimental validation. The modality set also excludes potentially informative assays such as proteomics, methylation, drug chemical structure, and lineage-aware representations. We report RMSE and MAE but do not provide a complete ranking-oriented evaluation using Pearson or Spearman correlation, and we do not test chemical-scaffold separation between training and held-out drugs. Source-specific AUC scales were retained rather than harmonized, so LOOD error magnitudes should not be read as directly comparable biological difficulty across datasets. No patient, organoid, PDX, or prospective external cohort was evaluated. Future work should enlarge the common-drug benchmark, compare response harmonization strategies, evaluate modality dropout and missingness-aware models, and predefine an external test set before model selection. These steps would test whether the observed transfer failure is specific to the current construction or a broader property of multimodal pharmacogenomics.")
    add_heading(doc, "5. Conclusion", 1)
    add_body(doc, "In this small, declared DepMap benchmark, adding copy-number and mutation blocks to expression produced a small mean improvement in drug-held-out prediction, but the direction changed across repeated splits and the improvement did not transfer to any of the three held-out source datasets. The result is therefore conditional rather than universal. The practical contribution is a reproducible comparison framework that makes the held-out entity, fold-local feature selection, structured availability, and transfer target explicit. Larger common-drug universes, external test sets, missingness-aware models, and alternative learners are needed before deciding whether the observed pattern generalizes beyond this Ridge-based construction.")
    add_heading(doc, "6. Data and code availability", 1)
    add_body(doc, "Code, manifests, derived result summaries, figures, and reproducibility notes are provided in the project repository. Raw DepMap files must be obtained from the provider under the applicable terms; see the public-data access note. The repository does not redistribute raw molecular matrices.")
    add_heading(doc, "7. References", 1)
    refs=["[1] Barretina J, et al. The Cancer Cell Line Encyclopedia enables predictive modelling of anticancer drug sensitivity. Nature. 2012;483:603–607. doi:10.1038/nature11003.","[2] Iorio F, et al. A landscape of pharmacogenomic interactions in cancer. Cell. 2016;166:740–754. doi:10.1016/j.cell.2016.06.017.","[3] Tsherniak A, et al. Defining a cancer dependency map. Cell. 2017;170:564–576.e16. doi:10.1016/j.cell.2017.06.010.","[4] Azuaje F. Computational models for predicting drug responses in cancer research. Brief Bioinform. 2017;18:820–829. doi:10.1093/bib/bbw065.","[5] Sharifi-Noghabi H, et al. MOLI: multi-omics late integration with deep neural networks for drug response prediction. Bioinformatics. 2019;35:i501–i509. doi:10.1093/bioinformatics/btz318.","[6] Cai Z, et al. Machine learning for multi-omics data integration in cancer. iScience. 2022;25:103798. doi:10.1016/j.isci.2022.103798.","[7] DepMap. How should I cite DepMap data? DepMap Portal. Updated 2025.","[8] Kuenzi BM, et al. Predicting drug response and synergy using a deep learning model of human cancer cells. Cancer Cell. 2020;38:672–684.e6. doi:10.1016/j.ccell.2020.09.014.","[9] Chawla S, Rockstroh A, Lehman M, et al. Gene expression based inference of cancer drug sensitivity. Nat Commun. 2022;13:5680. doi:10.1038/s41467-022-33291-z.","[10] Baptista D, Ferreira PG, Rocha M. Deep learning for drug response prediction in cancer. Brief Bioinform. 2023;24:bbac605. doi:10.1093/bib/bbac605.","[11] Gouru G. Precision oncology: Computational methods for multi-omics data integration to improve drug response prediction. Cambridge Prisms Precis Med. 2025;3:e6. doi:10.1017/pcm.2025.10003.","[12] Li D, et al. Multi-omics modality completion and knowledge distillation for drug response prediction in cervical cancer. Front Oncol. 2025;15:1622600. doi:10.3389/fonc.2025.1622600.","[13] Del Real KS, et al. Foundation models and deep learning for cancer drug response prediction: a framework for data, metrics, and validation. Brief Bioinform. 2026;27:bbag225. doi:10.1093/bib/bbag225."]
    for ref in refs: doc.add_paragraph(ref)

    doc.add_page_break(); add_heading(doc,"Appendix A. Reproducibility and reporting specification",1)
    add_body(doc,"This appendix makes explicit the decisions that determine the benchmark’s estimand. It is included so that a future implementation can reproduce the same comparison without inferring choices from code or from the headline results. The appendix is procedural: it does not add new biological claims.")
    add_heading(doc,"A.1. Analysis sequence",2)
    add_body(doc,"The analysis sequence is: (i) identify the declared response rows and source dataset; (ii) normalize identifiers and join modality matrices; (iii) create grouped split manifests; (iv) fit all preprocessing steps on training rows; (v) select the feature budget separately within each modality; (vi) transform training and test rows; (vii) fit the same Ridge specification for each modality and fusion; (viii) calculate MAE and RMSE on the held-out response rows; and (ix) write metrics, row counts, and manifest identifiers to machine-readable result files. The order is part of the method and should not be changed when comparing extensions.")
    p=doc.add_paragraph(); p.add_run("Table 5. ").bold=True; p.add_run("Reproducibility controls and their purpose.")
    add_table(doc,["Control","Implementation","Reason"],[
        ["Drug grouping","GroupShuffleSplit by drug_id_raw","Prevents the same drug response group crossing train/test"],
        ["Feature selection","Top 2,000 per modality inside training fold","Prevents test-informed feature ranking"],
        ["Imputation","Training-fold median applied to test rows","Avoids test-derived preprocessing parameters"],
        ["Scaling","Training-fold standardization","Places feature blocks on a common fitted scale"],
        ["Learner","Ridge, alpha = 1.0 for every block","Keeps the model comparison controlled"],
        ["Primary metrics","MAE and RMSE","Reports typical and squared-error sensitivity"],
        ["Transfer test","Hold out one full source dataset","Measures domain transfer rather than same-drug replication"],
    ])
    add_heading(doc,"A.2. Estimands and comparison rules",2)
    add_body(doc,"The primary within-universe estimand is the change in held-out response error produced by concatenating the three modality blocks relative to expression alone under the same drug-grouped split. The primary transfer estimand is the analogous change when the response source is held out in full. A negative fusion-minus-expression RMSE indicates lower error for fusion; a positive value indicates lower error for expression. No statistical significance claim is made from the five seeds or three transfer folds, because these are repeated benchmark partitions rather than independent biological experiments.")
    add_heading(doc,"A.3. Missingness and availability audit",2)
    add_body(doc,"Availability was audited before interpreting fusion results. For each source table, the audit records the number of rows with each modality available, the number complete across all selected blocks, and the number requiring imputation. Outer joins are used for this audit because an inner join can conceal the extent of modality-specific attrition. These counts characterize the constructed analysis table; they are not estimates of missingness in all DepMap data.")
    p=doc.add_paragraph(); p.add_run("Table 6. ").bold=True; p.add_run("Interpretation guardrails for the reported evidence.")
    add_table(doc,["Observed result","Permitted interpretation","Not supported"],[
        ["Fusion improves in 3 of 5 drug-held-out seeds","Small conditional improvement under this benchmark","Universal multimodal superiority"],
        ["Fusion worsens all 3 LOOD folds","Transfer failure in these source-held-out folds","Proof of a biological incompatibility"],
        ["Availability differs by dataset","Data structure is source-dependent","Missingness caused the error difference"],
        ["Modality correlations are weak-to-moderate","Some redundancy and complementarity coexist","A causal redundancy mechanism"],
        ["Ridge is reproducible and controlled","A transparent reference baseline","The best possible learner"],
        ["15 compounds are declared","Results are bounded to the declared universe","Generalization to all compounds"],
    ])
    add_heading(doc,"A.4. Recommended extensions",2)
    add_body(doc,"The next validation layer should preserve the current manifests while adding a larger common-drug universe and a completely external test partition. Candidate model extensions include late fusion with modality-specific regularization, modality dropout during training, explicit missingness indicators, and domain adaptation. Each extension should retain expression-only and single-modality baselines, report the same error metrics, and separate model selection from final evaluation. This will allow improvements in architecture to be distinguished from improvements caused by a more favorable split or response harmonization.")
    add_heading(doc,"A.5. Minimum reporting checklist for future comparisons",2)
    add_body(doc,"For comparability, future benchmark reports should identify the data release, response scale, compound inclusion rule, cell-line identifier rule, modality availability rule, feature-selection scope, imputation scope, split grouping variable, number of repeated seeds, model-selection procedure, primary baseline, primary metric, and external-transfer target. They should also report the number of rows entering each fold and the number excluded or imputed. These fields are more informative for interpretation than a single pooled accuracy value.")
    p=doc.add_paragraph(); p.add_run("Table 7. ").bold=True; p.add_run("Minimum fields to preserve with each future result table.")
    add_table(doc,["Field","Required record"],[["Data provenance","Provider, release label, download date, checksum"],["Population","Dataset, compound list, cell-line identifier, row count"],["Preprocessing","Imputation, scaling, filtering, feature-selection order"],["Validation","Split type, grouping unit, seed, train/test counts"],["Model","Modality, learner, hyperparameters, feature count"],["Performance","MAE, RMSE, delta to expression baseline"],["Availability","Complete rows, modality-specific availability, missing rows"],["Interpretation","Transfer target, limitations, and whether claims are causal"]])

    doc.add_page_break(); add_heading(doc,"Supplementary material",1)
    add_body(doc,"Supplementary Table S1 reports the declared compound universe and source-specific response rows. The initial three-seed missingness audit is reported separately in the frozen result tables; the five-seed performance benchmark is also reported separately. Supplementary Table S2 records the frozen artifact and validation scope. Figures are supplied separately in the submission package.")
    p=doc.add_paragraph(); p.add_run("Supplementary Table S2. ").bold=True; p.add_run("Drug-held-out missingness strata.")
    add_table(doc,["Seed","Complete rows","Missing rows","Total rows"],[["20260821","1513","1046","2559"],["20260822","1458","1271","2729"],["20260823","1530","1078","2608"]])
    p=doc.add_paragraph(); p.add_run("Supplementary Table S3. ").bold=True; p.add_run("Release scope and limitations.")
    add_table(doc,["Item","Status"],[["Evaluation universe","15 declared compounds across GDSC1, GDSC2, CTD²"],["Drug-held-out validation","5 persisted seeds; fold-local top-2,000 features from full raw modality universes"],["Cross-study validation","LOOD folds for CTD², GDSC1, and GDSC2"],["MoA mapping","15/15 declared compounds; 5/316 full GDSC1 universe"],["Raw data","Provider files not redistributed; checksums recorded"]])
    OUT.parent.mkdir(exist_ok=True); doc.save(OUT); print(OUT)

if __name__ == "__main__": main()
